In [259]:
import pandas as pd

In [260]:
df = pd.read_excel('exercicio_data_cleaning_RL_Base_Erro.xlsx')
df

       preco temperatura_c  umidade_pct dia_semana demanda
0          8            10         85.0          1     170
1        9.3          11.8         81.0          2  187 un
2       10.6          13.6         77.0          3     204
3       11.9          15.4         73.0          4     220
4    R$ 13,2          17.2          NaN          5     237
..       ...           ...          ...        ...     ...
115     15.6        24.4 C         51.6          4     268
116     16.9          26.2         47.6          5     284
117     18.2            28         43.6          6     301
118     19.5          29.8         39.6          7     318
119     20.8          31.6         35.6          1     250

[120 rows x 5 columns]

In [261]:
df['preco'] = (
    df['preco'].astype(str)
    .str.replace('R$', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.replace(' ', '', regex=False)
    .str.strip())

df['preco'] = pd.to_numeric(df['preco'], errors='coerce')

In [262]:
df['preco'].values

array([ 8. ,  9.3, 10.6, 11.9, 13.2, 14.5, 15.8, 17.1, 18.4, 19.7,  8.1,
        9.4, 10.7, 12. , 13.3, 14.6, 15.9, 17.2, 18.5, 19.8,  8.2,  9.5,
       10.8, 12.1, 13.4, 14.7, 16. , 17.3, 18.6, 19.9,  8.3,  9.6, 10.9,
       12.2, 13.5, 14.8, 16.1, 17.4, 18.7, 20. ,  8.4,  9.7, 11. , 12.3,
       13.6, 14.9, 16.2, 17.5, 18.8, 20.1,  8.5,  9.8, 11.1, 12.4, 13.7,
       15. , 16.3, 17.6, 18.9, 20.2,  8.6,  9.9, 11.2, 12.5, 13.8, 15.1,
       16.4, 17.7, 19. , 20.3,  8.7, 10. , 11.3, 12.6, 13.9, 15.2, 16.5,
       17.8, 19.1, 20.4,  8.8, 10.1, 11.4, 12.7, 14. , 15.3, 16.6, 17.9,
       19.2, 20.5,  8.9, 10.2, 11.5, 12.8, 14.1, 15.4, 16.7, 18. , 19.3,
       20.6,  9. , 10.3, 11.6, 12.9, 14.2, 15.5, 16.8, 18.1, 19.4, 20.7,
        9.1, 10.4, 11.7, 13. , 14.3, 15.6, 16.9, 18.2, 19.5, 20.8])

In [263]:
df['demanda'].values

array([170, '187 un', 204, 220, 237, 254, 270, 203, 219, 236, 356, 372,
       211, 227, 160, 177, 193, 210, 226, 243, 363, 295, 312, 329, 167,
       184, 200, 217, 150, 166, 286, 302, 319, 336, 352, 285, 123, 140,
       157, 173, 293, 310, '242 un', 259, 275, 292, 309, 325, 164, 96,
       216, 233, 249, 266, 282, '299 un', 232, 248, 265, 282, 223, 240,
       256, 189, 206, 222, '239 un', 255, 272, 289, 324, '341 un', 180,
       196, 213, 229, 246, 179, '195 un', 212, 332, '348 un', 365, 381,
       136, 152, '169 un', 186, 202, 219, 339, 271, 288, 304, 321, 338,
       176, 193, 125, 142, 262, 278, 295, 312, 328, 261, 277, 294, 132,
       149, 269, 285, 218, 235, 251, 268, 284, 301, 318, 250],
      dtype=object)

In [264]:
df['demanda'] = df['demanda'].astype(str).str.replace(' un', '', regex=False).str.strip()

In [265]:
df['demanda'].values

array(['170', '187', '204', '220', '237', '254', '270', '203', '219',
       '236', '356', '372', '211', '227', '160', '177', '193', '210',
       '226', '243', '363', '295', '312', '329', '167', '184', '200',
       '217', '150', '166', '286', '302', '319', '336', '352', '285',
       '123', '140', '157', '173', '293', '310', '242', '259', '275',
       '292', '309', '325', '164', '96', '216', '233', '249', '266',
       '282', '299', '232', '248', '265', '282', '223', '240', '256',
       '189', '206', '222', '239', '255', '272', '289', '324', '341',
       '180', '196', '213', '229', '246', '179', '195', '212', '332',
       '348', '365', '381', '136', '152', '169', '186', '202', '219',
       '339', '271', '288', '304', '321', '338', '176', '193', '125',
       '142', '262', '278', '295', '312', '328', '261', '277', '294',
       '132', '149', '269', '285', '218', '235', '251', '268', '284',
       '301', '318', '250'], dtype=object)

In [266]:
df['demanda'] = pd.to_numeric(df['demanda'], errors='coerce')

In [267]:
df['temperatura_c'].values

array([10, 11.8, 13.6, 15.4, 17.2, 19, 20.8, 22.6, 24.4, 26.2, 28, 29.8,
       '10.2 C', 12, 13.8, 15.6, 17.4, 19.2, 21, '22.8 C', 24.6, '26.4 C',
       28.2, 30, 10.4, 12.2, 14, 15.8, 17.6, 19.4, 21.2, 23, 24.8, 26.6,
       28.4, 30.2, 10.6, 12.4, 14.2, 16, 17.8, 19.6, 21.4, 23.2, 25,
       '26.8 C', 28.6, 30.4, 10.8, 12.6, 14.4, 16.2, 18, 19.8, 21.6, 23.4,
       25.2, 27, 28.8, '30.6 C', 11, 12.8, 14.6, 16.4, 18.2, 20, 21.8,
       23.6, 25.4, 27.2, 29, '30.8 C', 11.2, 13, 14.8, 16.6, 18.4, 20.2,
       22, 23.8, 25.6, '27,4 C', 29.2, 31, 11.4, 13.2, 15, 16.8, 18.6,
       20.4, 22.2, 24, 25.8, 27.6, 29.4, '31.2 C', 11.6, 13.4, 15.2, 17,
       18.8, 20.6, 22.4, 24.2, 26, 27.8, 29.6, 31.4, 11.8, 13.6, '15,4 C',
       17.2, 19, 20.8, 22.6, '24.4 C', 26.2, 28, 29.8, 31.6], dtype=object)

In [268]:
df['temperatura_c'] = df['temperatura_c'].astype(str).str.replace(' C', '', regex=False).str.replace(',', '.', regex=False).str.strip()

df['temperatura_c'].values

array(['10', '11.8', '13.6', '15.4', '17.2', '19', '20.8', '22.6', '24.4',
       '26.2', '28', '29.8', '10.2', '12', '13.8', '15.6', '17.4', '19.2',
       '21', '22.8', '24.6', '26.4', '28.2', '30', '10.4', '12.2', '14',
       '15.8', '17.6', '19.4', '21.2', '23', '24.8', '26.6', '28.4',
       '30.2', '10.6', '12.4', '14.2', '16', '17.8', '19.6', '21.4',
       '23.2', '25', '26.8', '28.6', '30.4', '10.8', '12.6', '14.4',
       '16.2', '18', '19.8', '21.6', '23.4', '25.2', '27', '28.8', '30.6',
       '11', '12.8', '14.6', '16.4', '18.2', '20', '21.8', '23.6', '25.4',
       '27.2', '29', '30.8', '11.2', '13', '14.8', '16.6', '18.4', '20.2',
       '22', '23.8', '25.6', '27.4', '29.2', '31', '11.4', '13.2', '15',
       '16.8', '18.6', '20.4', '22.2', '24', '25.8', '27.6', '29.4',
       '31.2', '11.6', '13.4', '15.2', '17', '18.8', '20.6', '22.4',
       '24.2', '26', '27.8', '29.6', '31.4', '11.8', '13.6', '15.4',
       '17.2', '19', '20.8', '22.6', '24.4', '26.2', '28', '29.8', '31.6'],
      dtype=object)

In [269]:
df['temperatura_c'] = pd.to_numeric(df['temperatura_c'], errors='coerce')

In [270]:
df['umidade_pct'].values

array([ 85. ,  81. ,  77. ,  73. ,   nan,  65. ,  61. ,  57. ,  53. ,
         nan,  45. ,  41. , 150. ,  80.4,   nan,  72.4,  68.4,  64.4,
        60.4,  56.4,  52.4,   nan,  44.4,  40.4,  83.8,   nan,  75.8,
        71.8,  67.8,  63.8,  59.8,  55.8,  51.8,   nan,  43.8,  39.8,
        -5. ,  79.2,  75.2,  71.2,  67.2,  63.2,  59.2,  55.2,  51.2,
        47.2,  43.2,  39.2,  82.6,  78.6,  74.6,  70.6,  66.6,  62.6,
        58.6,  54.6,  50.6,  46.6,  42.6,  38.6,   nan,  78. ,  74. ,
         nan,   nan,  62. ,  58. ,  54. ,  50. ,  46. ,  42. ,  38. ,
        81.4,  77.4,  73.4,  69.4,   nan,  61.4,  57.4,  53.4,  49.4,
        45.4,  41.4,  37.4,  80.8,  -5. ,  72.8,  68.8,  64.8,  60.8,
        56.8,  52.8,  48.8,  44.8,  40.8,  36.8,  80.2,  76.2,  72.2,
        68.2,  64.2,  60.2,  56.2,  52.2,  48.2,  44.2,  40.2,  36.2,
        79.6,  75.6,  71.6,  67.6, 150. ,  59.6,  55.6,  51.6,  47.6,
        43.6,  39.6,  35.6])

In [ ]:
df['umidade_pct'] = pd.to_numeric(df['umidade_pct'], errors='coerce')

df.loc[(df['umidade_pct'] < 0) | (df['umidade_pct'] > 100), 'umidade_pct'] = None

df['umidade_pct'] = df['umidade_pct'].fillna(df['umidade_pct'].mean())

df['umidade_pct'] = df['umidade_pct'].round(2)

In [272]:
df['umidade_pct'].values

array([85.  , 81.  , 77.  , 73.  , 59.19, 65.  , 61.  , 57.  , 53.  ,
       59.19, 45.  , 41.  , 59.19, 80.4 , 59.19, 72.4 , 68.4 , 64.4 ,
       60.4 , 56.4 , 52.4 , 59.19, 44.4 , 40.4 , 83.8 , 59.19, 75.8 ,
       71.8 , 67.8 , 63.8 , 59.8 , 55.8 , 51.8 , 59.19, 43.8 , 39.8 ,
       59.19, 79.2 , 75.2 , 71.2 , 67.2 , 63.2 , 59.2 , 55.2 , 51.2 ,
       47.2 , 43.2 , 39.2 , 82.6 , 78.6 , 74.6 , 70.6 , 66.6 , 62.6 ,
       58.6 , 54.6 , 50.6 , 46.6 , 42.6 , 38.6 , 59.19, 78.  , 74.  ,
       59.19, 59.19, 62.  , 58.  , 54.  , 50.  , 46.  , 42.  , 38.  ,
       81.4 , 77.4 , 73.4 , 69.4 , 59.19, 61.4 , 57.4 , 53.4 , 49.4 ,
       45.4 , 41.4 , 37.4 , 80.8 , 59.19, 72.8 , 68.8 , 64.8 , 60.8 ,
       56.8 , 52.8 , 48.8 , 44.8 , 40.8 , 36.8 , 80.2 , 76.2 , 72.2 ,
       68.2 , 64.2 , 60.2 , 56.2 , 52.2 , 48.2 , 44.2 , 40.2 , 36.2 ,
       79.6 , 75.6 , 71.6 , 67.6 , 59.19, 59.6 , 55.6 , 51.6 , 47.6 ,
       43.6 , 39.6 , 35.6 ])

In [277]:
df['dia_semana'].values

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1,
       2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2,
       3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3,
       4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4,
       5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5,
       6, 7, 1, 2, 3, 4, 5, 6, 7, 1])

In [274]:
mapa_dias = {
    'seg': 1,
    'ter': 2,
    'qua': 3,
    'qui': 4,
    'sex': 5,
    'sab': 6,
    'dom': 7
}

def padronizar_dia(valor):
    if isinstance(valor, str):
        valor = valor.strip().lower()
        return mapa_dias.get(valor, None)
    else:
        return valor

df['dia_semana'] = df['dia_semana'].apply(padronizar_dia)

In [275]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   preco          120 non-null    float64
 1   temperatura_c  120 non-null    float64
 2   umidade_pct    120 non-null    float64
 3   dia_semana     120 non-null    int64
 4   demanda        120 non-null    int64
dtypes: float64(3), int64(2)
memory usage: 4.8 KB

In [276]:
df.describe()

            preco  temperatura_c  umidade_pct  dia_semana     demanda
count  120.000000     120.000000   120.000000  120.000000  120.000000
mean    14.400000      20.800000    59.190500    3.975000  246.066667
std      3.765612       6.266357    12.948959    2.018663   63.727062
min      8.000000      10.000000    35.600000    1.000000   96.000000
25%     11.175000      15.400000    49.250000    2.000000  199.000000
50%     14.400000      20.800000    59.190000    4.000000  247.000000
75%     17.625000      26.200000    68.950000    6.000000  293.250000
max     20.800000      31.600000    85.000000    7.000000  381.000000

In [279]:
df.to_csv('DadosLimpos_Venda_Sorvete.csv', index=False)